### ISSUE TITLE
Could I use atlantic18n DoctrineExtension with a2lix?

### ISSUE THREAD

**Issue by asgardia7** [a2lix/TranslationFormBundle#253] opened 2016-12-21 09:39 UTC
Hello,

I used to use atlantic18n DoctrineExtension (stof in symfony) with gedmo with a2lixTranslationFormBundle. I got error missing entityTranslation class now. At least could I use it without Personal Translations but only Entity Translation?
Any you, the best case is I could use it without separate Entity Translation for each entity.

Thanks please :)

**Comment by jordisala1991** [comment] 2018-03-04 21:46
This is duplicate of, https://github.com/a2lix/TranslationFormBundle/issues/187

Closing

**Closed by jordisala1991** 2018-03-04 21:46 UTC
