### ISSUE TITLE
Required fields in non-required locales

### ISSUE THREAD

**Issue by Starojitski** [a2lix/TranslationFormBundle#272] opened 2017-11-01 14:09 UTC
I have two languages `NL` (required) and `EN` (optional) and translation class with a required `name`, and optional `description` fields.
Form can not be submitted without `NL` translation of `name`. Trying  to save `EN` translation with `description` but without `name` sends data via POST to the server where an exception is generated:
```
An exception occurred while executing 
'INSERT INTO section_translation (name, description, locale, translatable_id) 
VALUES (?, ?, ?, ?, ?)' with params [null, "test description", "en", 60]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'description' cannot be null
```
Is there a way to trigger client side validation of optional locale translation when some of its fields are filled in?

**Comment by jordisala1991** [comment] 2018-03-04 21:55
Assertions on entities and/or on the form types should work the same as you do on other fields outside translations.

With the option 'constraints' on each field inside the form builder, or using asserts directly via annotations on the entities.

Don't forget to add a constraint over the 'translation' field to force it to be valid.

This does not seem like an issue/bug on our side, but a lack of configuration/code to handle your problem.

Closing for now. If you feel this should remain open because the issue is still there, feel free to ping me to reopen and provide further information.

Docs could probably have more examples.

**Closed by jordisala1991** 2018-03-04 21:55 UTC

**Comment by comur** [comment] 2019-09-26 13:47
Hi,

I have the same issue. I have all asserts in translation entity. If a locale is not required, validation doesn't work and I have a violation exception.

**Comment by jerome-fix** [comment] 2019-09-27 03:58
Hi,

Hereafter the explanation from @jordisala1991

> Don't forget to add a constraint over the 'translation' field to force it to be valid.

Simply add this annotations to your code : 

```php
 /**
     * @Assert\Valid()
     */
    protected $translations;
```
Jérôme.

**Comment by Bluestart83** [comment] 2024-02-10 14:54
I have also the same issue and make my own trait and adding  this do nothing:
```

   #[Assert\Valid]
    protected $translations;

    /**
     * @see mergeNewTranslations
     * @var Collection<string, TranslationInterface>
     */
    #[Assert\Valid]
    protected $newTranslations;
```

**Comment by Bluestart83** [comment] 2024-02-10 14:59
May be you could add it to your traits one for attribute mode and one for annotations.
